### ISSUE TITLE
Support for mouse button 5 and 4 to go up/down a directory

### ISSUE THREAD

**Issue by 7erra** [SteezCram/PboViewer#1]
It would be nice to be able to use the mouse buttons to navigate the folder structure. Mouse button 5 (the back one on the side) normally brings you into the parent directory of the current folder while mouse button 4 (front one) takes you into the last subfolder.

**Comment by SteezCram** [comment]
Hello,

If I understand:
- button 5 to go to the parent directory
- button 4 to navigate on a subfolder

I will look to implement it

**Comment by SteezCram** [comment]
Maybe I have found a better way to do it:
- I have set the focus to the list box
- You can navigate through the directional arrow
- You will be able to press enter to open the file or navigate to a folder

Tell me if it's good.

**Comment by 7erra** [comment]
I am not sure I can follow? I usually have my hand on the mouse when navigating files, so just pressing those mouse buttons is more comfortable than moving the cursor and clicking.

**Comment by SteezCram** [comment]
I have understood, it's navigating buttons you want. It will be more difficult to implement it since the concept of navigation doesn't exist in the application.

So I need to create it from scratch.

EDIT: I will implement the keyboard navigation first and then the navigation

**Comment by SteezCram** [comment]
The keyboard navigation has been implemented, I will look to make the navigation available.

I release once I done it.

**Comment by SteezCram** [comment]
Avalonia doesn't support mouse buttons 4 and 5, I will make an issue about it.

**Comment by SteezCram** [comment]
I have published a new version with experimental support of keyboard navigation.

You can read more in the wiki.
