### ISSUE TITLE
Clicks will not open the selected item when the mouse has not been moved since last time

### ISSUE THREAD

**Issue by 7erra** [SteezCram/PboViewer#2]
**Describe the bug**
When double clicking a folder and then trying to double click another item will not work. Moving the mouse will fix this issue.

**To Reproduce**
1. Open a pbo
2. Double click on a folder
3. Do NOT move your mouse
4. Double clicking the item (folder or file) under the mouse will do nothing

**Expected behavior**
Double clicking should open the item

**Screenshots**
https://user-images.githubusercontent.com/38866692/111082799-70965680-850a-11eb-9fe7-d1f79abba112.mp4

**Operating system**
Edition:	Windows 10 Home
Version:	20H2
Installed on:	‎10.‎09.‎2020
OS Build:	19042.867
Performance: Windows Feature Experience Pack 120.2212.551.0

**Additional context**
Tested on 3den.pbo in Arma 3's Addon folder

EDIT: Formatting for bug template

**Comment by SteezCram** [comment]
Hello, please can you add a video to describe your problem?

**Comment by 7erra** [comment]
https://user-images.githubusercontent.com/38866692/111082799-70965680-850a-11eb-9fe7-d1f79abba112.mp4

I also updated the original task description to follow the template

**Comment by SteezCram** [comment]
Yes, thanks, I can reproduce it, but I think I cannot resolve this given that it depends on the graphic library that I use for my project: Avalonia.

In fact, it seems to trigger the event (here navigate through a folder) when you double click and not when you click multiple times (even if you double click at the start). I try to find some workaround but I cannot guarantee to solve it.
