### ISSUE TITLE
PBO Viewer does not extract a full mission.sqm file

### ISSUE THREAD

**Issue by SgtFoose** [SteezCram/PboViewer#4]
I'm using the latest viewer from https://github.com/SteezCram/PboViewer/releases, it works when extracting the pbo file but mission.sqm stops at line 36810? Any clue why?
![IMG_2936](https://user-images.githubusercontent.com/17387175/205488059-0cd0af43-7274-454c-aa25-2d2baa50a9df.jpg)

**Comment by SteezCram** [comment]
Hello, can you send me your file to test?

**Comment by SgtFoose** [comment]
Here you go:

PBO File:
https://www.dropbox.com/s/whjrxbbd65tkjo6/co40_domination_4_63_blufor_HUD_v_01.altis.pbo?dl=0

Missions.sqm from admin (working):
https://www.dropbox.com/s/k7dtievilpeqdkb/mission.sqm?dl=0

**Comment by SteezCram** [comment]
Yes, your PBO seems to have bad headers, can you try packing the original folder with PBO Viewer?

**Comment by SgtFoose** [comment]
> Yes, your PBO seems to have bad headers, can you try packing the original folder with PBO Viewer?

Sorry I do not have access to the original since it came from playing on an online server.
I downloaded many pbo's from this server for past 5 years. This is the first time the mission file exceeded 42340 lines (class Item712) of code (this was on game version 4_57).

**Comment by SteezCram** [comment]
I need more time to analyze the problem, I will try to solve it, but I think it won't be easy.
