### ISSUE TITLE
Problems with libssl on Ubuntu 22.04

### ISSUE THREAD

**Issue by mve1983** [SteezCram/PboViewer#5]
On Ubuntu 22.04. LTS: 
1. GUI Binary for Ubuntu won't run or return an error. 
2. Linux CLI will return error "No usable version of the libssl was found"

Can be fixed by installing the needed dependency.
`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb`
`sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb`

After adding the needed dependency:
1. GUI will run and work as expected. 
2. CLI also works as expected.

**Comment by SteezCram** [comment]
Hello, sorry for the late response.

I know why you need libssl it is for the checksum functions. Unfortunately, I should not shipped directly with the program.
However, you should have libssl by default on Ubuntu.

**Comment by mve1983** [comment]
Hi, no problem, it was a fresh install of 22.04 LTS Ubuntu. 
I don't have this problem on other machine with Ubuntu 20.04.
Maybe it was only my machine, then thread should be closed.
Or maybe it's because Ubuntu 22.04 only supports openssl 3.0 by default install?

**Comment by zatricky** [comment]
The libssl1 package is an old library which is why Ubuntu 22.04 doesn't even offer it (libssl3 is installed by default and is the current version). I'm not sure if this is the right link - but in theory this would have been fixed in upstream last year:
https://github.com/dotnet/core/issues/7038

**Comment by SteezCram** [comment]
Ok, I will update the .Net version

**Comment by SteezCram** [comment]
It should be solved, a new release has been made
